---
# OS Setup Role - Handlers

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Restart tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted
